In [2]:
import pandas as pd

In [55]:
df = pd.read_csv("main_data_lstm.csv")

In [57]:
df.drop(['Unnamed: 0','data_set','R35_4qAVG','ID','time'], axis = 1, inplace=True)

In [58]:
df.head()

lon   lat  Vmax   MSLP
0 -50.3  35.8  55.0  992.0
1 -49.9  35.5  55.0  990.0
2 -49.5  35.1  55.0  989.0
3 -49.1  34.8  55.0  988.0
4 -48.7  34.4  55.0  986.0

In [59]:
df.shape

(4580, 4)

In [60]:
new_order=['lat','lon','Vmax','MSLP']
df = df.reindex(columns=new_order)  # reindex using function

In [61]:
df.sample()

lat    lon  Vmax   MSLP
2794 -14.4  100.8  40.0  993.0

In [62]:
arr=df.values
arrlist=arr.tolist()

In [63]:
df.shape
arrlist

[[35.8, -50.3, 55.0, 992.0],
 [35.5, -49.9, 55.0, 990.0],
 [35.1, -49.5, 55.0, 989.0],
 [34.8, -49.1, 55.0, 988.0],
 [34.4, -48.7, 55.0, 986.0],
 [34.0, -48.2, 52.0, 986.0],
 [33.7, -47.8, 50.0, 987.0],
 [33.5, -47.4, 48.0, 988.0],
 [33.2, -47.0, 45.0, 988.0],
 [33.0, -46.5, 45.0, 988.0],
 [32.7, -46.1, 45.0, 989.0],
 [32.5, -45.7, 42.0, 990.0],
 [32.3, -45.3, 40.0, 991.0],
 [32.2, -45.0, 40.0, 992.0],
 [32.1, -44.7, 40.0, 993.0],
 [32.0, -44.5, 38.0, 994.0],
 [31.9, -44.4, 35.0, 994.0],
 [31.8, -44.2, 35.0, 994.0],
 [31.6, -44.1, 35.0, 995.0],
 [31.4, -43.8, 32.0, 996.0],
 [31.1, -43.5, 30.0, 996.0],
 [31.1, -43.0, 30.0, 996.0],
 [31.1, -42.6, 30.0, 996.0],
 [31.2, -42.2, 30.0, 996.0],
 [31.3, -41.8, 30.0, 996.0],
 [31.5, -41.5, 30.0, 996.0],
 [31.7, -41.1, 30.0, 996.0],
 [31.9, -40.8, 30.0, 996.0],
 [32.1, -40.4, 30.0, 996.0],
 [32.5, -40.0, 30.0, 996.0],
 [32.8, -39.6, 30.0, 996.0],
 [33.3, -39.4, 32.0, 995.0],
 [33.8, -39.2, 35.0, 994.0],
 [34.6, -39.4, 35.0, 994.0],
 [35.4, -39.6,

In [64]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from keras.models import Sequential
from keras.layers import LSTM, Dense

In [65]:
from sklearn.model_selection import train_test_split

In [68]:
x=[]
y=[]
for i in range(4577):
   s=[]
   s.append(arrlist[i])
   s.append(arrlist[i+1])
   s.append(arrlist[i+2])
   x.append(s) 
   y.append(arrlist[i+3][0:2])

In [69]:
s

[[8.4, 104.7, 20.0, 1007.0],
 [8.4, 104.4, 20.0, 1007.0],
 [8.4, 104.0, 18.0, 1009.0]]

In [70]:
y

[[34.8, -49.1],
 [34.4, -48.7],
 [34.0, -48.2],
 [33.7, -47.8],
 [33.5, -47.4],
 [33.2, -47.0],
 [33.0, -46.5],
 [32.7, -46.1],
 [32.5, -45.7],
 [32.3, -45.3],
 [32.2, -45.0],
 [32.1, -44.7],
 [32.0, -44.5],
 [31.9, -44.4],
 [31.8, -44.2],
 [31.6, -44.1],
 [31.4, -43.8],
 [31.1, -43.5],
 [31.1, -43.0],
 [31.1, -42.6],
 [31.2, -42.2],
 [31.3, -41.8],
 [31.5, -41.5],
 [31.7, -41.1],
 [31.9, -40.8],
 [32.1, -40.4],
 [32.5, -40.0],
 [32.8, -39.6],
 [33.3, -39.4],
 [33.8, -39.2],
 [34.6, -39.4],
 [35.4, -39.6],
 [36.3, -40.2],
 [37.3, -40.7],
 [38.1, -41.9],
 [39.0, -43.0],
 [39.5, -44.6],
 [40.0, -46.3],
 [40.0, -47.8],
 [39.9, -49.3],
 [39.2, -50.0],
 [38.5, -50.8],
 [37.4, -51.0],
 [36.3, -51.2],
 [35.5, -50.6],
 [34.7, -50.0],
 [33.8, -49.4],
 [32.8, -48.7],
 [32.3, -47.5],
 [31.9, -46.4],
 [7.5, -49.6],
 [7.7, -50.7],
 [7.8, -51.7],
 [7.9, -52.8],
 [8.1, -53.9],
 [8.3, -55.2],
 [8.6, -56.5],
 [8.9, -57.7],
 [9.2, -58.9],
 [9.4, -59.7],
 [9.7, -60.5],
 [10.1, -61.3],
 [10.4, -62.1],
 [2

In [71]:
x

[[[35.8, -50.3, 55.0, 992.0],
  [35.5, -49.9, 55.0, 990.0],
  [35.1, -49.5, 55.0, 989.0]],
 [[35.5, -49.9, 55.0, 990.0],
  [35.1, -49.5, 55.0, 989.0],
  [34.8, -49.1, 55.0, 988.0]],
 [[35.1, -49.5, 55.0, 989.0],
  [34.8, -49.1, 55.0, 988.0],
  [34.4, -48.7, 55.0, 986.0]],
 [[34.8, -49.1, 55.0, 988.0],
  [34.4, -48.7, 55.0, 986.0],
  [34.0, -48.2, 52.0, 986.0]],
 [[34.4, -48.7, 55.0, 986.0],
  [34.0, -48.2, 52.0, 986.0],
  [33.7, -47.8, 50.0, 987.0]],
 [[34.0, -48.2, 52.0, 986.0],
  [33.7, -47.8, 50.0, 987.0],
  [33.5, -47.4, 48.0, 988.0]],
 [[33.7, -47.8, 50.0, 987.0],
  [33.5, -47.4, 48.0, 988.0],
  [33.2, -47.0, 45.0, 988.0]],
 [[33.5, -47.4, 48.0, 988.0],
  [33.2, -47.0, 45.0, 988.0],
  [33.0, -46.5, 45.0, 988.0]],
 [[33.2, -47.0, 45.0, 988.0],
  [33.0, -46.5, 45.0, 988.0],
  [32.7, -46.1, 45.0, 989.0]],
 [[33.0, -46.5, 45.0, 988.0],
  [32.7, -46.1, 45.0, 989.0],
  [32.5, -45.7, 42.0, 990.0]],
 [[32.7, -46.1, 45.0, 989.0],
  [32.5, -45.7, 42.0, 990.0],
  [32.3, -45.3, 40.0, 991.0]],

In [72]:
xtrain=np.array(x)

In [73]:
xtrain.shape

(4577, 3, 4)

In [74]:
ytrain=np.array(y)

In [75]:
ytrain

array([[ 34.8, -49.1],
       [ 34.4, -48.7],
       [ 34. , -48.2],
       ...,
       [  8.4, 104.4],
       [  8.4, 104. ],
       [  8.5, 103.6]])

In [76]:
import tensorflow as tf
from tensorflow.keras import layers
from keras.layers import Dense
from keras.layers import LSTM
from keras.models import Sequential

In [77]:
# create the LSTM model
model = Sequential()
from keras.layers import Input
model.add(layers.Input(shape=(3,4)))
model.add(LSTM(128,activation='LeakyReLU',return_sequences=False))
model.add(Dense(2,activation='LeakyReLU'))

In [78]:
model.compile(optimizer='adam', loss='mean_squared_error')

In [79]:
model.fit(xtrain,ytrain,epochs=200)

Epoch 1/200
144/144 [==============================] - 6s 18ms/step - loss: 810.4219
Epoch 2/200
144/144 [==============================] - 3s 18ms/step - loss: 50.7889
Epoch 3/200
144/144 [==============================] - 3s 18ms/step - loss: 44.3714
Epoch 4/200
144/144 [==============================] - 3s 18ms/step - loss: 39.0688
Epoch 5/200
144/144 [==============================] - 2s 17ms/step - loss: 42.0798
Epoch 6/200
144/144 [==============================] - 3s 18ms/step - loss: 37.5723
Epoch 7/200
144/144 [==============================] - 2s 17ms/step - loss: 36.0272
Epoch 8/200
144/144 [==============================] - 2s 17ms/step - loss: 37.3063
Epoch 9/200
144/144 [==============================] - 2s 17ms/step - loss: 33.2503
Epoch 10/200
144/144 [==============================] - 3s 18ms/step - loss: 33.6986
Epoch 11/200
144/144 [==============================] - 2s 17ms/step - loss: 33.2299
Epoch 12/200
144/144 [==============================] - 3s 18ms/step - lo

In [80]:
output=model.predict(xtrain)
ytrain[:,1]

array([-49.1, -48.7, -48.2, ..., 104.4, 104. , 103.6])

In [81]:
output[:,1]

array([-49.694958, -49.25278 , -48.818897, ..., 106.38214 , 105.948   ,
       105.89381 ], dtype=float32)

In [82]:
from sklearn.metrics import r2_score

In [83]:
r2_score(output[:,1],ytrain[:,1])

0.996930140322064

In [84]:
output

array([[ 35.785374, -49.694958],
       [ 35.517456, -49.25278 ],
       [ 35.155457, -48.818897],
       ...,
       [  8.353296, 106.38214 ],
       [  8.612818, 105.948   ],
       [  8.515097, 105.89381 ]], dtype=float32)

In [85]:
df.sample(5) 

lat    lon  Vmax    MSLP
1594  21.1 -121.2  55.0   996.0
3242   9.8  115.9  20.0  1007.0
2533 -22.4   32.1  25.0  1004.0
4434  10.4  116.9  33.0   998.0
3976  20.4  120.2  30.0  1000.0

In [86]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_3 (LSTM)               (None, 128)               68096     
                                                                 
 dense_2 (Dense)             (None, 2)                 258       
                                                                 
Total params: 68,354
Trainable params: 68,354
Non-trainable params: 0
_________________________________________________________________


In [87]:
model.save("Final2.h5")

In [51]:
df.shape

(53, 4)

In [52]:
model.predict([[[33.8, -49.4, 38.0, 998.0],
 [32.8, -48.7, 35.0, 999.0],
 [32.3, -47.5, 32.0, 1000.0]]])

array([[ 33.499672, -46.870457]], dtype=float32)